#!/usr/bin/env node
/**
 * build-docx.js: generate an IMRaD research article DOCX from a manuscript folder.
 *
 * Usage:
 *   node build-docx.js --manuscript <dir> [--out paper.docx]
 *
 * Reads <dir>/config.yaml (title, authors, journal; a small line-based subset of
 * YAML, no dependency) and <dir>/sections/*.md, assembling them in IMRaD order:
 * abstract, introduction, methods, results, discussion, conclusion,
 * acknowledgments, references, then anything else alphabetically.
 *
 * Implements the subset of templates/word/article-imrad.md that a first draft
 * needs: A4, 1-inch margins, Times New Roman 12pt, double spacing, a title
 * page, numbered Heading 1-3 (Abstract, Acknowledgments, and References stay
 * unnumbered per the spec), page numbers from page 2, and a References heading.
 *
 * Supported markdown subset (documented contract, tested in test/):
 *   #, ##, ### headings; paragraphs; **bold**; *italic*; `code` (rendered as
 *   monospace); - bullet lists. Tables, tracked changes, and comments are NOT
 *   generated by this script yet; they remain planned work (see the word-output
 *   skill for the roadmap).
 *
 * Images: automatic figure embedding is still planned, so by default a
 * markdown image line (![alt](src)) is rendered as a visible "[Figure: alt]"
 * placeholder that preserves the alt text rather than embedding the binary.
 * The real embedding path is wired and correct: pass --embed-images and every
 * emitted image carries its alt text in the DOCX accessibility properties
 * (<wp:docPr descr=... title=...>), which is what screen readers announce.
 * The alt text MUST describe the figure's DATA content, not its styling
 * (see references/figure-styles.md); build-docx only carries through whatever
 * the markdown alt text supplies.
 *
 * Built on the `docx` library (npm install inside templates/word/).
 */

const fs = require("fs");
const path = require("path");

let docx;
try {
  docx = require("docx");
} catch (err) {
  if (err.code !== "MODULE_NOT_FOUND") throw err;
  console.error(
    "build-docx: the 'docx' library is not installed.\n" +
    "Install it once, then re-run this script:\n" +
    "\n" +
    "  cd templates/word\n" +
    "  npm ci\n" +
    "\n" +
    "(npm install also works; package-lock.json is tracked, so npm ci is preferred.)"
  );
  process.exit(1);
}

const {
  AlignmentType, Document, Footer, HeadingLevel, ImageRun, PageNumber, Packer, Paragraph, TextRun,
} = docx;

const SECTION_ORDER = [
  "abstract", "introduction", "methods", "results", "discussion",
  "conclusion", "acknowledgments", "references",
];
const UNNUMBERED = new Set(["abstract", "acknowledgments", "references", "appendix"]);

const TWIPS_PER_INCH = 1440;
const A4 = { width: 11906, height: 16838 };
const BODY = { font: "Times New Roman", size: 24 }; // half-points: 12pt

function parseArgs(argv) {
  const args = { out: "paper.docx" };
  for (let i = 2; i < argv.length; i++) {
    if (argv[i] === "--manuscript") args.manuscript = argv[++i];
    else if (argv[i] === "--out") args.out = argv[++i];
  }
  args.embedImages = argv.includes("--embed-images");
  if (!args.manuscript) {
    console.error("Usage: node build-docx.js --manuscript <dir> [--out paper.docx] [--embed-images]");
    process.exit(2);
  }
  return args;
}

/** Minimal config.yaml reader: top-level `key: value` plus a block list of
 * authors (either `- name: X` maps or plain `- X` strings). */
function readConfig(manuscriptDir) {
  const config = { title: "Untitled Manuscript", authors: [] };
  const file = path.join(manuscriptDir, "config.yaml");
  if (!fs.existsSync(file)) return config;
  const lines = fs.readFileSync(file, "utf-8").split(/\r?\n/);
  let inAuthors = false;
  for (const line of lines) {
    if (/^authors\s*:/.test(line)) { inAuthors = true; continue; }
    if (inAuthors) {
      const item = line.match(/^\s+-\s*(?:name\s*:\s*)?(.+)$/);
      if (item) { config.authors.push(item[1].trim().replace(/^["']|["']$/g, "")); continue; }
      const nested = line.match(/^\s+\w+\s*:/); // other keys of an author map: skip
      if (nested) continue;
      inAuthors = false;
    }
    const kv = line.match(/^(\w+)\s*:\s*(.+)$/);
    if (kv) config[kv[1]] = kv[2].trim().replace(/^["']|["']$/g, "");
  }
  return config;
}

/** Inline markdown: **bold**, *italic*, `code`. Returns TextRun[]. */
function inlineRuns(text) {
  const runs = [];
  const pattern = /(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)/g;
  let last = 0;
  for (const match of text.matchAll(pattern)) {
    if (match.index > last) runs.push(new TextRun({ text: text.slice(last, match.index), ...BODY }));
    const token = match[0];
    if (token.startsWith("**")) {
      runs.push(new TextRun({ text: token.slice(2, -2), bold: true, ...BODY }));
    } else if (token.startsWith("`")) {
      runs.push(new TextRun({ text: token.slice(1, -1), font: "Courier New", size: 22 }));
    } else {
      runs.push(new TextRun({ text: token.slice(1, -1), italics: true, ...BODY }));
    }
    last = match.index + token.length;
  }
  if (last < text.length) runs.push(new TextRun({ text: text.slice(last), ...BODY }));
  return runs.length ? runs : [new TextRun({ text, ...BODY })];
}

const DOUBLE = { line: 480, lineRule: "auto" };

// Content width in pixels (96 dpi): A4 minus the two 1-inch side margins.
const MAX_IMAGE_WIDTH_PX = Math.round(((A4.width - 2 * TWIPS_PER_INCH) / TWIPS_PER_INCH) * 96);
const IMAGE_LINE_RE = /^!\[([^\]]*)\]\(([^)]+)\)\s*$/;

/** Intrinsic pixel size of a PNG (from the IHDR chunk) or null if not a PNG. */
function pngDimensions(buf) {
  if (buf.length < 24 || buf.readUInt32BE(0) !== 0x89504e47) return null;
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

/** Intrinsic pixel size of a JPEG (from the first SOF marker) or null. */
function jpegDimensions(buf) {
  if (buf.length < 4 || buf[0] !== 0xff || buf[1] !== 0xd8) return null;
  let off = 2;
  while (off + 9 < buf.length) {
    if (buf[off] !== 0xff) { off++; continue; }
    const marker = buf[off + 1];
    // SOF0..SOF15 carry the frame dimensions; skip DHT (C4), DAC (CC), RSTn.
    if (marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc) {
      return { height: buf.readUInt16BE(off + 5), width: buf.readUInt16BE(off + 7) };
    }
    off += 2 + buf.readUInt16BE(off + 2);
  }
  return null;
}

/** Build a centered paragraph embedding an image, with the alt text written
 * into the DOCX accessibility properties. This is the single place image alt
 * text is plumbed, so any future image feature routes through here and stays
 * accessible. `altText` must describe the figure's DATA content, not styling. */
function imageParagraph(altText, absPath) {
  const data = fs.readFileSync(absPath);
  const ext = path.extname(absPath).toLowerCase();
  const type = ext === ".jpg" || ext === ".jpeg" ? "jpg" : ext.replace(/^\./, "") || "png";
  const intrinsic =
    (type === "png" ? pngDimensions(data) : type === "jpg" ? jpegDimensions(data) : null) ||
    { width: MAX_IMAGE_WIDTH_PX, height: Math.round((MAX_IMAGE_WIDTH_PX * 3) / 4) };
  const scale = intrinsic.width > MAX_IMAGE_WIDTH_PX ? MAX_IMAGE_WIDTH_PX / intrinsic.width : 1;
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: DOUBLE,
    children: [new ImageRun({
      type,
      data,
      transformation: {
        width: Math.round(intrinsic.width * scale),
        height: Math.round(intrinsic.height * scale),
      },
      // Alt text flows to <wp:docPr descr=... title=...>, what screen readers read.
      altText: { title: altText, description: altText, name: path.basename(absPath) },
    })],
  });
}

/** Render a markdown image line. Default: a visible "[Figure: alt]" placeholder
 * that preserves the alt text (image embedding is still planned). With
 * --embed-images and a resolvable source file, embed the real image carrying
 * its alt text. Either way the alt text is never dropped. */
function imageLineParagraph(altText, src, manuscriptDir, embedImages) {
  if (embedImages) {
    const abs = path.resolve(manuscriptDir, src);
    if (fs.existsSync(abs)) return imageParagraph(altText, abs);
    console.error(`build-docx: image not found, keeping alt-text placeholder: ${src}`);
  }
  const label = altText.trim() ? `[Figure: ${altText.trim()}]` : `[Figure: ${src}]`;
  return new Paragraph({
    spacing: DOUBLE,
    children: [new TextRun({ text: label, italics: true, ...BODY })],
  });
}

function headingParagraph(text, level, counters, sectionKey) {
  let label = text;
  if (!UNNUMBERED.has(sectionKey)) {
    if (level === 1) { counters.h1++; counters.h2 = 0; counters.h3 = 0; label = `${counters.h1}. ${text}`; }
    if (level === 2) { counters.h2++; counters.h3 = 0; label = `${counters.h1}.${counters.h2} ${text}`; }
    if (level === 3) { counters.h3++; label = `${counters.h1}.${counters.h2}.${counters.h3} ${text}`; }
  }
  const size = level === 1 ? 28 : 24; // 14pt / 12pt
  return new Paragraph({
    heading: [HeadingLevel.HEADING_1, HeadingLevel.HEADING_2, HeadingLevel.HEADING_3][level - 1],
    spacing: { before: [480, 360, 240][level - 1], ...DOUBLE },
    children: [new TextRun({
      text: label, bold: level < 3, italics: level === 3,
      font: BODY.font, size, color: "000000",
    })],
  });
}

/** Convert one markdown section body to docx paragraphs. */
function sectionParagraphs(sectionKey, title, markdown, counters, opts = {}) {
  const { manuscriptDir = ".", embedImages = false } = opts;
  const paragraphs = [headingParagraph(title, 1, counters, sectionKey)];
  const lines = markdown.split(/\r?\n/);
  let buffer = [];
  const flush = () => {
    const text = buffer.join(" ").trim();
    if (text) {
      paragraphs.push(new Paragraph({ spacing: DOUBLE, children: inlineRuns(text) }));
    }
    buffer = [];
  };
  for (const raw of lines) {
    const line = raw.replace(/<!--.*?-->/g, "");
    const heading = line.match(/^(#{1,3})\s+(.*)$/);
    if (heading) {
      flush();
      const level = heading[1].length;
      if (level === 1) continue; // the section title itself; already emitted
      paragraphs.push(headingParagraph(heading[2].trim(), level, counters, sectionKey));
      continue;
    }
    const image = line.match(IMAGE_LINE_RE);
    if (image) {
      flush();
      paragraphs.push(imageLineParagraph(image[1], image[2].trim(), manuscriptDir, embedImages));
      continue;
    }
    const bullet = line.match(/^\s*[-*]\s+(.*)$/);
    if (bullet) {
      flush();
      paragraphs.push(new Paragraph({
        spacing: DOUBLE, bullet: { level: 0 }, children: inlineRuns(bullet[1]),
      }));
      continue;
    }
    if (!line.trim()) { flush(); continue; }
    buffer.push(line.trim());
  }
  flush();
  return paragraphs;
}

function titlePage(config) {
  const children = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 2 * TWIPS_PER_INCH },
      children: [new TextRun({ text: config.title, bold: true, font: BODY.font, size: 32 })],
    }),
  ];
  if (config.authors.length) {
    children.push(new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 480 },
      children: [new TextRun({ text: config.authors.join(", "), ...BODY })],
    }));
  }
  if (config.journal) {
    children.push(new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 240 },
      children: [new TextRun({ text: `Prepared for: ${config.journal}`, italics: true, font: BODY.font, size: 20 })],
    }));
  }
  return children;
}

function collectSections(manuscriptDir) {
  const dir = path.join(manuscriptDir, "sections");
  if (!fs.existsSync(dir)) {
    console.error(`No sections/ directory in ${manuscriptDir}`);
    process.exit(2);
  }
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".md"));
  const keyOf = (f) => path.basename(f, ".md").toLowerCase();
  files.sort((a, b) => {
    const ia = SECTION_ORDER.indexOf(keyOf(a));
    const ib = SECTION_ORDER.indexOf(keyOf(b));
    return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib) || a.localeCompare(b);
  });
  return files.map((f) => ({
    key: keyOf(f),
    title: keyOf(f).replace(/(^|\s)\w/g, (c) => c.toUpperCase()),
    body: fs.readFileSync(path.join(dir, f), "utf-8"),
  }));
}

async function main() {
  const args = parseArgs(process.argv);
  const config = readConfig(args.manuscript);
  const sections = collectSections(args.manuscript);

  const counters = { h1: 0, h2: 0, h3: 0 };
  const children = titlePage(config);
  for (const section of sections) {
    children.push(...sectionParagraphs(section.key, section.title, section.body, counters, {
      manuscriptDir: args.manuscript,
      embedImages: args.embedImages,
    }));
  }

  const doc = new Document({
    styles: { default: { document: { run: BODY } } },
    sections: [{
      properties: {
        page: {
          size: A4,
          margin: { top: TWIPS_PER_INCH, bottom: TWIPS_PER_INCH, left: TWIPS_PER_INCH, right: TWIPS_PER_INCH },
        },
        titlePage: true, // page numbers start on page 2
      },
      headers: {},
      footers: {
        default: new Footer({
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ children: [PageNumber.CURRENT], ...BODY })],
          })],
        }),
        first: new Footer({ children: [] }),
      },
      children,
    }],
  });

  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(args.out, buffer);
  console.log(`Wrote ${args.out} (${sections.length} sections, ${buffer.length} bytes)`);
}

main().catch((err) => {
  console.error(`build-docx failed: ${err.message}`);
  process.exit(1);
});
